version: '3.5'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    network_mode: "host"  
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  db:
    container_name: postgres
    image: postgres:latest
    env_file: ./configs/db/database.conf
    ports:
      - 5432:5432  
    volumes:
      - ./db/:/var/lib/postgresql
  krakend:
    build:
      context: krakend
      dockerfile: Dockerfile
    container_name: krakend
    network_mode: "host"
    env_file: ./configs/krakend/app.conf
    volumes:
      - ./configs/krakend:/etc/krakend
    ports:
      - 8090:8080
    command: [ "run", "-c", "/etc/krakend/config.json" ]

  json_2_xml:
    build:
      context: json2xml-transformer
      dockerfile: Dockerfile
    container_name: json_2_xml
    ports:
      - 6501:5000
    depends_on:
      - krakend

  record_repository:
    build:
      context: record-repository
      dockerfile: Dockerfile
    container_name: record_repository
    env_file: ./configs/record-repository/app.conf
    ports:
      - 6502:5000
    depends_on:
      - krakend
      - db
  file_repository:
    build:
      context: file-repository
      dockerfile: Dockerfile
    container_name: file_repository
    env_file: ./configs/file-repository/app.conf
    volumes:
      - ./file-repository/storage/:/app/storage/
    network_mode: "host"
    ports:
      - 6504:6504
    command: uvicorn server:app --host 0.0.0.0 --port 5004
    depends_on:
      - krakend
      - redis
      - db

  ftp_worker:
    build:
      context: file-repository
      dockerfile: Dockerfile.worker
    container_name: ftp_worker
    env_file: ./configs/file-repository/app.conf
    volumes:
      - ./file-repository/storage/:/app/storage/
    depends_on:
      - file_repository
      - redis
  
  redis:
    image: redis:4.0.6-alpine
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis:/data


  smev_connector:
    build:
      context: smev-connector
      dockerfile: Dockerfile
    container_name: smev_connector
    env_file: ./configs/smev-connector/app.conf
    volumes:
      - ./log_raw:/app/raw/
      - ./configs/smev-connector:/app/configs
    ports:
      - 6503:6503
    network_mode: "host"
    command: uvicorn main:app --host 0.0.0.0 --port 5003
    depends_on:
      - krakend
      - db

  redoc:
    image: redocly/redoc
    container_name: redoc
    ports:
      - 6580:80
    volumes:
      - ./redoc:/usr/share/nginx/html/swagger/
    env_file: ./redoc/app.conf
    depends_on:
      - krakend
  wiki:
    image: squidfunk/mkdocs-material
    container_name: wiki
    ports:
      - 6581:8000
    volumes:
      - ./_docs:/docs

  plugin_app:
    build:
      context: plugins
      dockerfile: Dockerfile
    container_name: plugin_app
    env_file: ./configs/plugins/app.conf
    ports:
      - 6505:6505
    network_mode: "host"
    command: uvicorn main:app --host 0.0.0.0 --port 6505
    volumes:
      - ./plugins/tmp:/app/tmp/
    depends_on:
      - krakend
