site_name: Smev 3 client
nav:
  - Home: index.md
  - Architecture Description: architecture-description.md
  - Core API Components:
    - Json2xml: json2xml.md
    - Xml Signer: xml-signer.md
    - Smev Connector: smev-connector.md
    - Record Repository: record-repository.md
    - File Repository: file-repository.md
  - External API / Plugins:
    - Ros Reestr: rosreestr_plugin.md
  - Raw Examples:
    - Ros Reestr: raw_requests_ros_reestr.md
    - Ð•eply To an Incomming Request:  raw_requests_reply_incomming_request.md
theme:
  name: 'material'
